### ISSUE TITLE
failed to create directory in devcontainer

### ISSUE THREAD

**Issue by randallard** [randallard/rust-postgres#4]
Removed /usr/local/cargo/registry/cache because I kept getting this error after rebuilding the container and running the watch
```

Updating crates.io index
  Downloaded foreign-types-shared v0.1.1
error: failed to download replaced source registry `crates-io`

Caused by:
  failed to create directory `/usr/local/cargo/registry/cache/index.crates.io-6f17d22bba15001f`

Caused by:
  Permission denied (os error 13)
```

added it back in with sudo mkdir but still getting the error

after the container is built it the permissions are

```
vscode ➜ /workspaces $ ls -la  /usr/local/cargo/registry
total 28
drwxr-sr-x 5 root   rustlang 4096 Oct 30 16:27 .
drwxrwsrwx 1 vscode rustlang 4096 Oct 30 16:27 ..
drwxr-sr-x 3 root   rustlang 4096 Oct 30 16:27 cache
-rw-r--r-- 1 root   rustlang  177 Oct 30 16:28 CACHEDIR.TAG
drwxr-sr-x 3 root   rustlang 4096 Oct 30 16:27 index
drwxr-sr-x 3 root   rustlang 4096 Oct 30 16:27 src
```

**Comment by randallard** [comment]
watch succeded after 


`sudo chown -R vscode:rustlang /usr/local/cargo/registry`

**Comment by randallard** [comment]
tried adding CMD line to the end of Dockerfile but it didn't run - maybe should be added to compose?

**Comment by randallard** [comment]
@tharpooljha 
I got tired of waiting for the build over and over - want to get back to coding but let me know your thoughts and if you want to mess with this - assign back to me when you want me to take over - not an urgent issue

**Comment by tharpooljha** [comment]
Removing the localworkspace folder seems to do the trick. Closing
